export const viewConfigs = {
  zsd124: {
    id: "ZSGV_ZSD124",
    title: "订单 BOM 过账",
    source: "SAP HANA 视图 ZSGV_ZSD124",
    detail: "查看物料过账、订单关联和客户信息。",
    dateField: "BUDAT_MKPF",
    showProductionOrder: true,
    showSalesOrder: true,
    showProductModel: false,
    bilingual: false,
    allowMissingSalesOrderExport: true,
    stats: [
      { key: "productionOrders", label: "生产订单数量（去重）", tone: "green" },
      { key: "salesOrders", label: "销售订单数量（去重）", tone: "orange" },
      { key: "missingSalesOrder", label: "销售订单为空", tone: "orange" },
      { key: "missingProductionOrder", label: "生产订单为空", tone: "red" },
      {
        key: "missingProductionOrderDistinct",
        label: "生产订单为空（去重）",
        tone: "red",
      },
    ],
    advancedFields: [{ key: "materialCode", placeholder: "物料号 / Material" }],
    columns: [
      "MBLNR",
      "MJAHR",
      "ZEILE",
      "MATNR",
      "WERKS",
      "BWART",
      "MENGE_A",
      "AUFNR_1",
      "VBELN_EX",
      "BUDAT_MKPF",
    ],
    columnLabels: {
      MBLNR: "物料凭证号",
      MJAHR: "物料凭证年度",
      ZEILE: "物料凭证行项目",
      MATNR: "物料号",
      WERKS: "工厂",
      BWART: "移动类型",
      MENGE_A: "数量",
      AUFNR_1: "生产订单",
      VBELN_EX: "销售订单",
      BUDAT_MKPF: "过账日期",
    },
  },
  sernolist: {
    id: "ZSGV_ZPP_SERNOLIST",
    title: "序列号绑定 / Serial Number Binding",
    source: "SAP HANA 视图 / SAP HANA View ZSGV_ZPP_SERNOLIST",
    detail:
      "查看大刀、 小刀序列号与生产订单、产品层次的绑定关系 / View binding between head, item serial numbers, production orders and product hierarchy.",
    dateField: "",
    showProductionOrder: false,
    showSalesOrder: false,
    showProductModel: true,
    bilingual: true,
    advancedFields: [
      { key: "headOrder", placeholder: "机头订单 / Head order" },
      { key: "itemOrder", placeholder: "小刀订单 / Item order" },
    ],
    columns: ["ZCODE_HEAD", "ZCODE_ITEM", "AUFNR_HEAD", "AUFNR_ITEM", "PRODH"],
    columnLabels: {
      ZCODE_HEAD: "大刀/机头序列号（ZCODE_HEAD）",
      ZCODE_ITEM: "小刀/BOX序列号（ZCODE_ITEM）",
      AUFNR_HEAD: "大刀/机头生产订单号（AUFNR_HEAD）",
      AUFNR_ITEM: "小刀/BOX生产订单号（AUFNR_ITEM）",
      PRODH: "产品层次（PRODH）",
    },
  },
  station: {
    id: "Z_V_ZMES_T_001",
    title: "工位记录",
    source: "SAP HANA 视图 Z_V_ZMES_T_001（BW_LOCAL.ZTRRI）",
    detail: "查看生产工位、工序和实际开始结束时间。",
    dateField: "ACTUAL_START_TIME",
    showProductionOrder: true,
    showSalesOrder: true,
    showProductModel: true,
    bilingual: false,
    stats: [
      { key: "missingSalesOrder", label: "销售订单为空", tone: "orange" },
      { key: "missingProductionOrder", label: "生产订单为空", tone: "red" },
    ],
    advancedFields: [
      { key: "sn", placeholder: "主机序列号 / PCODE" },
      { key: "stationCode", placeholder: "工位 / Station" },
      { key: "base", placeholder: "基地 / Base" },
    ],
    columns: [
      "HISTROYID",
      "PCODE",
      "OCODE",
      "AUFNR",
      "SPEC",
      "OPERATION",
      "GSTRS",
      "ACTUAL_START_TIME",
      "ACTUAL_END_TIME",
    ],
    columnLabels: {
      HISTROYID: "主键（HISTROYID）",
      PCODE: "主机序列号（PCODE）",
      OCODE: "客户序列号（OCODE）",
      AUFNR: "生产订单（AUFNR）",
      SPEC: "操作工序（SPEC）",
      OPERATION: "操作说明（OPERATION）",
      GSTRS: "计划开始日期（GSTRS）",
      ACTUAL_START_TIME: "实际开始时间（ACTUAL_START_TIME）",
      ACTUAL_END_TIME: "实际结束时间（ACTUAL_END_TIME）",
    },
  },
};
export const viewById = Object.fromEntries(
  Object.values(viewConfigs).map((config) => [config.id, config]),
);
