export const viewConfigs = {
  zsd124: {
    id: "ZSGV_ZSD124",
    title: "订单 BOM 过账",
    source: "SAP HANA 视图 ZSGV_ZSD124",
    detail: "查看物料过账、订单关联和客户信息。",
    dateField: "BUDAT_MKPF",
    showProductionOrder: true,
    showSalesOrder: true,
    showProductModel: false,
    bilingual: false,
    allowMissingSalesOrderExport: true,
    stats: [
      { key: "productionOrders", label: "生产订单数量（去重）", tone: "green" },
      { key: "salesOrders", label: "销售订单数量（去重）", tone: "orange" },
      { key: "missingSalesOrder", label: "销售订单为空", tone: "orange" },
      { key: "missingProductionOrder", label: "生产订单为空", tone: "red" },
      {
        key: "missingProductionOrderDistinct",
        label: "生产订单为空（去重）",
        tone: "red",
      },
    ],
    advancedFields: [{ key: "materialCode", placeholder: "物料号 / Material" }],
    columns: [
      "MBLNR",
      "MJAHR",
      "ZEILE",
      "MATNR",
      "WERKS",
      "BWART",
      "MENGE_A",
      "AUFNR_1",
      "VBELN_EX",
      "BUDAT_MKPF",
    ],
    columnLabels: {
      MBLNR: "物料凭证号",
      MJAHR: "物料凭证年度",
      ZEILE: "物料凭证行项目",
      MATNR: "物料号",
      WERKS: "工厂",
      BWART: "移动类型",
      MENGE_A: "数量",
      AUFNR_1: "生产订单",
      VBELN_EX: "销售订单",
      BUDAT_MKPF: "过账日期",
    },
  },
  sernolist: {
    id: "ZSGV_ZPP_SERNOLIST",
    title: "序列号绑定 / Serial Number Binding",
    source: "SAP HANA 视图 / SAP HANA View ZSGV_ZPP_SERNOLIST",
    detail:
      "查看大刀、 小刀序列号与生产订单、产品层次的绑定关系 / View binding between head, item serial numbers, production orders and product hierarchy.",
    dateField: "",
    showProductionOrder: false,
    showSalesOrder: false,
    showProductModel: true,
    bilingual: true,
    advancedFields: [
      { key: "headOrder", placeholder: "机头订单 / Head order" },
      { key: "itemOrder", placeholder: "小刀订单 / Item order" },
    ],
    columns: ["ZCODE_HEAD", "ZCODE_ITEM", "AUFNR_HEAD", "AUFNR_ITEM", "PRODH"],
    columnLabels: {
      ZCODE_HEAD: "大刀/机头序列号（ZCODE_HEAD）",
      ZCODE_ITEM: "小刀/BOX序列号（ZCODE_ITEM）",
      AUFNR_HEAD: "大刀/机头生产订单号（AUFNR_HEAD）",
      AUFNR_ITEM: "小刀/BOX生产订单号（AUFNR_ITEM）",
      PRODH: "产品层次（PRODH）",
    },
  },
  station: {
    id: "Z_V_ZMES_T_001",
    title: "工位记录",
    source: "SAP HANA 视图 Z_V_ZMES_T_001（BW_LOCAL.ZTRRI）",
    detail: "查看生产工位、工序和实际开始结束时间。",
    dateField: "ACTUAL_START_TIME",
    showProductionOrder: true,
    showSalesOrder: true,
    showProductModel: true,
    bilingual: false,
    stats: [
      { key: "missingSalesOrder", label: "销售订单为空", tone: "orange" },
      { key: "missingProductionOrder", label: "生产订单为空", tone: "red" },
    ],
    advancedFields: [
      { key: "sn", placeholder: "主机序列号 / PCODE" },
      { key: "stationCode", placeholder: "工位 / Station" },
      { key: "base", placeholder: "基地 / Base" },
    ],
    columns: [
      "HISTROYID",
      "PCODE",
      "OCODE",
      "AUFNR",
      "SPEC",
      "OPERATION",
      "GSTRS",
      "ACTUAL_START_TIME",
      "ACTUAL_END_TIME",
    ],
    columnLabels: {
      HISTROYID: "主键（HISTROYID）",
      PCODE: "主机序列号（PCODE）",
      OCODE: "客户序列号（OCODE）",
      AUFNR: "生产订单（AUFNR）",
      SPEC: "操作工序（SPEC）",
      OPERATION: "操作说明（OPERATION）",
      GSTRS: "计划开始日期（GSTRS）",
      ACTUAL_START_TIME: "实际开始时间（ACTUAL_START_TIME）",
      ACTUAL_END_TIME: "实际结束时间（ACTUAL_END_TIME）",
    },
  },
  scsDoa: {
    id: "SCS_DOA",
    title: "SCS DOA 申报",
    source: "SCS 平台 DOA 申报（scs_doa_records）",
    detail: "按申报、服务单、设备和产品实体信息检索 SCS DOA 数据。",
    dateField: "declare_time",
    showProductionOrder: false,
    showSalesOrder: false,
    showProductModel: false,
    bilingual: false,
    advancedFields: [
      { key: "doaCode", placeholder: "DOA申报单号" },
      { key: "serviceOrder", placeholder: "服务单号 / SH" },
      {
        key: "status",
        type: "select",
        label: "处理状态",
        placeholder: "处理状态",
        options: [
          { value: "待受理", label: "待受理" },
          { value: "已受理", label: "已受理" },
        ],
      },
      { key: "customer", placeholder: "客户全称" },
      {
        key: "judgment",
        type: "select",
        label: "判定结果",
        placeholder: "判定结果",
        options: [
          { value: "是", label: "是" },
          { value: "否", label: "否" },
        ],
      },
      { key: "salesOrder", placeholder: "销售订单" },
      { key: "company5000", type: "checkbox", label: "是否为5000公司" },
    ],
    columns: [
      "doa_code", "doa_type", "service_uid", "status", "doa_judge", "customer_uid",
      "sugon_sn", "spare_part_sn", "product_name", "review_name", "shipment_date",
      "engineer_uid", "problem_conclusion", "declare_uid", "declare_time", "acceptance_time", "sales_order", "is_5000_company",
    ],
    columnLabels: {
      doa_code: "DOA申报单号", doa_type: "DOA类型", service_uid: "服务单号", status: "处理状态",
      doa_judge: "判定结果", customer_uid: "客户全称", sugon_sn: "曙光S/N", spare_part_sn: "备件S/N",
      product_name: "产品/备件名称", review_name: "问题描述", shipment_date: "发货日期", engineer_uid: "工程师",
      problem_conclusion: "问题分析结论", declare_uid: "申报人", declare_time: "申报时间", acceptance_time: "受理时间", sales_order: "销售订单", is_5000_company: "是否为5000公司",
    },
    columnClasses: {
      doa_judge: "column-judgment",
      customer_uid: "column-customer",
    },
    compactStatusColumns: ["doa_judge"],
  },
  scsChange: {
    id: "SCS_CHANGE",
    title: "SCS 换上换下",
    source: "SCS 平台数据查询（scs_change_records）",
    detail: "检索服务单备件换上、换下操作及 5000 公司归属。",
    dateField: "create_time",
    showProductionOrder: false,
    showSalesOrder: false,
    showProductModel: false,
    bilingual: false,
    advancedFields: [
      { key: "serviceOrder", placeholder: "服务单号" },
      { key: "customer", placeholder: "客户名称" },
      { key: "sn", placeholder: "报修设备 SN" },
      { key: "changeType", placeholder: "操作类型（换上-up / 换下-down）" },
      { key: "partNumber", placeholder: "备件 PN" },
      { key: "partSn", placeholder: "备件 SN" },
      { key: "operator", placeholder: "操作人" },
      { key: "needReturn", placeholder: "是否需要归还" },
      { key: "revoked", placeholder: "是否撤销" },
      { key: "company5000", type: "checkbox", label: "是否为5000公司" },
    ],
    columns: [
      "so_code", "customer_name", "device_sn", "change_type", "part_number", "part_sn",
      "part_name", "original_code", "remark", "need_return", "operator", "create_time",
      "is_revoked", "revoked_by", "revoked_time", "is_5000_company",
    ],
    columnLabels: {
      so_code: "服务单号", customer_name: "客户名称", device_sn: "报修设备", change_type: "操作类型",
      part_number: "PN", part_sn: "SN", part_name: "备件名称", original_code: "原厂原码", remark: "备注",
      need_return: "是否需要归还", operator: "操作人", create_time: "操作时间", is_revoked: "是否撤销",
      revoked_by: "撤销人", revoked_time: "撤销时间", is_5000_company: "是否为5000公司",
    },
  },
};
export const viewById = Object.fromEntries(
  Object.values(viewConfigs).map((config) => [config.id, config]),
);
